apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  labels:
    project: version-management
data:
  script.sh: |-
    #!/bin/bash
    if [[ "$POD_NAME" = "mongodb-0"]];
    then
      export MONGODB_REPLICA_SET_MODE="primary"
    else
      export MONGODB_INITIAL_PRIMARY_PORT_NUMBER="27017"
      export MONGODB_REPLICA_SET_MODE="SECONDARY"
    fi
    exec /opt/bitnami/scripts/mongodb/entrypoint.sh /opt/bitnami/scripts/mongodb/run.sh