apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap-bin
data:
  {{- (.Files.Glob .Values.config.bin).AsConfig | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap-etc
data:
 {{- (.Files.Glob .Values.config.etc).AsConfig | nindent 2}}