apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-pv-0
spec:
  capacity:
    storage: {{ .Values.pod.volumeClaimTemplates[0].storage }}
  storageClassName: {{ .Values.pod.volumeClaimTemplates[0].storageClassName }}
  accessModes: {{ .Values.pod.volumeClaimTemplates[0].accessModes }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongodb/pv-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-pv-1
spec:
  capacity:
    storage: {{ .Values.pod.volumeClaimTemplates[0].storage }}
  storageClassName: {{ .Values.pod.volumeClaimTemplates[0].storageClassName }}
  accessModes: {{ .Values.pod.volumeClaimTemplates[0].accessModes }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongodb/pv-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName }}-pv-2
spec:
  capacity:
    storage: {{ .Values.pod.volumeClaimTemplates[0].storage }}
  storageClassName: {{ .Values.pod.volumeClaimTemplates[0].storageClassName }}
  accessModes: {{ .Values.pod.volumeClaimTemplates[0].accessModes }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongodb/pv-2
