apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.appName }}-secret-env
data:
  DATABASE_NAME: {{ .Values.secret.databaseName }} 
  ADMIN_USER: {{ .Values.secret.adminUser }}
  ADMIN_PASSWORD: {{ .Values.secret.adminPassword }}
  REPLICA_USER: {{ .Values.secret.replicaUser }}
  REPLICA_PASSWORD: {{ .Values.secret.replicaPassword }}
  TIMESTART: {{ .Values.secret.timeBeforeInitPrimaryKeyNode }}
