apiVersion: v1 
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  selector:
    app: {{ .Values.service.selector.app }}
    env: {{ .Values.service.selector.env }}
    project: {{ .Values.service.selector.project }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end}}
