apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.appName }}-stateful-set
  labels:
    project: {{ .Values.labels.project }}
    env: {{ .Values.labels.env }}
    app: {{ .Values.labels.app }}
spec:
  serviceName: {{ .Values.appName }}-service
  replicas: {{ .Values.pod.replicas }}
  selector: 
    matchLabels:
      project: {{ .Values.labels.project }}
      env: {{ .Values.labels.env }}
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        project: {{ .Values.labels.project }}
        env: {{ .Values.labels.env }}
        app: {{ .Values.labels.app }}
    spec:
      containers:
      - name: {{ .Values.pod.container.containerName }}
        image: {{ .Values.pod.container.image }}
        ports:
        {{- range .Values.service.ports }}
        - containerPort: {{ .targetPort }}
        {{- end }}
        volumeMounts:
        - name: {{ .Values.appName }}-etc
          mountPath: {{ .Values.pod.container.volumes.etc.mountPath }}
        - name: {{ .Values.appName }}-bin
          mountPath: {{ .Values.pod.container.volumes.bin.mountPath }}
        - name: {{ .Values.appName }}-data
          mountPath: {{ .Values.pod.container.volumes.data.mountPath }}
        command: ["/data/bin/start.sh"]
        env:
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}-secret-env
                key: ADMIN_USER
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}-secret-env
                key: ADMIN_PASSWORD
          - name: REPLICA_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}-secret-env
                key: REPLICA_USER
          - name: REPLICA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}-secret-env
                key: REPLICA_PASSWORD
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}-secret-env
                key: DATABASE_NAME
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}-secret-env
                key: DATABASE_NAME
          - name: TIMESTART
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}-secret-env
                key: TIMESTART
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: REPLICA_CLUSTER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}-secret-env
                key: REPLICA_CLUSTER
          - name: NUMBER_REPLICA
            valueFrom:
              secretKeyRef:
                name: {{ .Values.appName }}-secret-env
                key: NUMBER_REPLICA
      volumes:
      - name: {{ .Values.appName }}-etc
        configMap:
          name: {{ .Values.appName }}-configmap-etc
          defaultMode: {{ .Values.pod.container.volumes.etc.mode }}
      - name: {{ .Values.appName }}-bin
        configMap:
          name: {{ .Values.appName }}-configmap-bin
          defaultMode: {{ .Values.pod.container.volumes.bin.mode }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.appName }}-data
    spec:
      resources:
        requests:
          storage: {{ .Values.pod.volumeClaimTemplates.storage }}
      accessModes: {{ .Values.pod.volumeClaimTemplates.accessModes}}
      storageClassName: {{ .Values.pod.volumeClaimTemplates.storageClassName }}
      
